package com.example.study.object;

public class Unit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.id
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.unit_key
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    private String unitKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.type
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.name
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.address
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.coordinate
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    private String coordinate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.id
     *
     * @return the value of unit.id
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.id
     *
     * @param id the value for unit.id
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.unit_key
     *
     * @return the value of unit.unit_key
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    public String getUnitKey() {
        return unitKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.unit_key
     *
     * @param unitKey the value for unit.unit_key
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    public void setUnitKey(String unitKey) {
        this.unitKey = unitKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.type
     *
     * @return the value of unit.type
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.type
     *
     * @param type the value for unit.type
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.name
     *
     * @return the value of unit.name
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.name
     *
     * @param name the value for unit.name
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.address
     *
     * @return the value of unit.address
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.address
     *
     * @param address the value for unit.address
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.coordinate
     *
     * @return the value of unit.coordinate
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    public String getCoordinate() {
        return coordinate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.coordinate
     *
     * @param coordinate the value for unit.coordinate
     *
     * @mbg.generated Sun May 19 18:46:17 CST 2019
     */
    public void setCoordinate(String coordinate) {
        this.coordinate = coordinate;
    }
}