package com.example.study.object;

public class Administrator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.unit_id
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.id
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.name
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.phone
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.account_name
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.account_password
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    private String accountPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.unit_id
     *
     * @return the value of administrator.unit_id
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.unit_id
     *
     * @param unitId the value for administrator.unit_id
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.id
     *
     * @return the value of administrator.id
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.id
     *
     * @param id the value for administrator.id
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.name
     *
     * @return the value of administrator.name
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.name
     *
     * @param name the value for administrator.name
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.phone
     *
     * @return the value of administrator.phone
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.phone
     *
     * @param phone the value for administrator.phone
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.account_name
     *
     * @return the value of administrator.account_name
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.account_name
     *
     * @param accountName the value for administrator.account_name
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.account_password
     *
     * @return the value of administrator.account_password
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    public String getAccountPassword() {
        return accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.account_password
     *
     * @param accountPassword the value for administrator.account_password
     *
     * @mbg.generated Mon May 06 09:30:31 CST 2019
     */
    public void setAccountPassword(String accountPassword) {
        this.accountPassword = accountPassword;
    }
}