package com.example.study.object;

public class Receiver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.unit_id
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.id
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.name
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.gender
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.phone
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.account_name
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.account_password
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    private String accountPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.status
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.task_id
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    private String taskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.unit_id
     *
     * @return the value of receiver.unit_id
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.unit_id
     *
     * @param unitId the value for receiver.unit_id
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.id
     *
     * @return the value of receiver.id
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.id
     *
     * @param id the value for receiver.id
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.name
     *
     * @return the value of receiver.name
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.name
     *
     * @param name the value for receiver.name
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.gender
     *
     * @return the value of receiver.gender
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.gender
     *
     * @param gender the value for receiver.gender
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.phone
     *
     * @return the value of receiver.phone
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.phone
     *
     * @param phone the value for receiver.phone
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.account_name
     *
     * @return the value of receiver.account_name
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.account_name
     *
     * @param accountName the value for receiver.account_name
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.account_password
     *
     * @return the value of receiver.account_password
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public String getAccountPassword() {
        return accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.account_password
     *
     * @param accountPassword the value for receiver.account_password
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public void setAccountPassword(String accountPassword) {
        this.accountPassword = accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.status
     *
     * @return the value of receiver.status
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.status
     *
     * @param status the value for receiver.status
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.task_id
     *
     * @return the value of receiver.task_id
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.task_id
     *
     * @param taskId the value for receiver.task_id
     *
     * @mbg.generated Mon May 06 09:30:53 CST 2019
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }
}