package com.example.study.object;

public class Rescuer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rescuer.unit_id
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rescuer.id
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rescuer.name
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rescuer.gender
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rescuer.phone
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rescuer.open_id
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rescuer.avater
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    private String avater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rescuer.status
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rescuer.task_id
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    private String taskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rescuer.unit_id
     *
     * @return the value of rescuer.unit_id
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rescuer.unit_id
     *
     * @param unitId the value for rescuer.unit_id
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rescuer.id
     *
     * @return the value of rescuer.id
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rescuer.id
     *
     * @param id the value for rescuer.id
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rescuer.name
     *
     * @return the value of rescuer.name
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rescuer.name
     *
     * @param name the value for rescuer.name
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rescuer.gender
     *
     * @return the value of rescuer.gender
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rescuer.gender
     *
     * @param gender the value for rescuer.gender
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rescuer.phone
     *
     * @return the value of rescuer.phone
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rescuer.phone
     *
     * @param phone the value for rescuer.phone
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rescuer.open_id
     *
     * @return the value of rescuer.open_id
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rescuer.open_id
     *
     * @param openId the value for rescuer.open_id
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rescuer.avater
     *
     * @return the value of rescuer.avater
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public String getAvater() {
        return avater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rescuer.avater
     *
     * @param avater the value for rescuer.avater
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public void setAvater(String avater) {
        this.avater = avater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rescuer.status
     *
     * @return the value of rescuer.status
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rescuer.status
     *
     * @param status the value for rescuer.status
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rescuer.task_id
     *
     * @return the value of rescuer.task_id
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rescuer.task_id
     *
     * @param taskId the value for rescuer.task_id
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }
}