package com.example.study.object;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.status
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.type
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.user_open_id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    private String userOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.rescuer_open_id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    private String rescuerOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.chat_group_id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    private String chatGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.receiver_id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    private String receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.event_location_name
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    private String eventLocationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.event_location_coordinate
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    private String eventLocationCoordinate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.aid_location_name
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    private String aidLocationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.aid_location_coordinate
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    private String aidLocationCoordinate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.aid_route
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    private String aidRoute;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.id
     *
     * @return the value of task.id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.id
     *
     * @param id the value for task.id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.status
     *
     * @return the value of task.status
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.status
     *
     * @param status the value for task.status
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.type
     *
     * @return the value of task.type
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.type
     *
     * @param type the value for task.type
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.user_open_id
     *
     * @return the value of task.user_open_id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public String getUserOpenId() {
        return userOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.user_open_id
     *
     * @param userOpenId the value for task.user_open_id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public void setUserOpenId(String userOpenId) {
        this.userOpenId = userOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.rescuer_open_id
     *
     * @return the value of task.rescuer_open_id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public String getRescuerOpenId() {
        return rescuerOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.rescuer_open_id
     *
     * @param rescuerOpenId the value for task.rescuer_open_id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public void setRescuerOpenId(String rescuerOpenId) {
        this.rescuerOpenId = rescuerOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.chat_group_id
     *
     * @return the value of task.chat_group_id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public String getChatGroupId() {
        return chatGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.chat_group_id
     *
     * @param chatGroupId the value for task.chat_group_id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public void setChatGroupId(String chatGroupId) {
        this.chatGroupId = chatGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.receiver_id
     *
     * @return the value of task.receiver_id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.receiver_id
     *
     * @param receiverId the value for task.receiver_id
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.event_location_name
     *
     * @return the value of task.event_location_name
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public String getEventLocationName() {
        return eventLocationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.event_location_name
     *
     * @param eventLocationName the value for task.event_location_name
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public void setEventLocationName(String eventLocationName) {
        this.eventLocationName = eventLocationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.event_location_coordinate
     *
     * @return the value of task.event_location_coordinate
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public String getEventLocationCoordinate() {
        return eventLocationCoordinate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.event_location_coordinate
     *
     * @param eventLocationCoordinate the value for task.event_location_coordinate
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public void setEventLocationCoordinate(String eventLocationCoordinate) {
        this.eventLocationCoordinate = eventLocationCoordinate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.aid_location_name
     *
     * @return the value of task.aid_location_name
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public String getAidLocationName() {
        return aidLocationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.aid_location_name
     *
     * @param aidLocationName the value for task.aid_location_name
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public void setAidLocationName(String aidLocationName) {
        this.aidLocationName = aidLocationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.aid_location_coordinate
     *
     * @return the value of task.aid_location_coordinate
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public String getAidLocationCoordinate() {
        return aidLocationCoordinate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.aid_location_coordinate
     *
     * @param aidLocationCoordinate the value for task.aid_location_coordinate
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public void setAidLocationCoordinate(String aidLocationCoordinate) {
        this.aidLocationCoordinate = aidLocationCoordinate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.aid_route
     *
     * @return the value of task.aid_route
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public String getAidRoute() {
        return aidRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.aid_route
     *
     * @param aidRoute the value for task.aid_route
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    public void setAidRoute(String aidRoute) {
        this.aidRoute = aidRoute;
    }
}