package com.example.study.mapper;

import com.example.study.object.Rescuer;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface RescuerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rescuer
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    @Delete({
        "delete from rescuer",
        "where unit_id = #{unitId,jdbcType=VARCHAR}",
          "and id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("unitId") String unitId, @Param("id") String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rescuer
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    @Insert({
        "insert into rescuer (unit_id, id, ",
        "name, gender, phone, ",
        "open_id, avater, ",
        "status, task_id)",
        "values (#{unitId,jdbcType=VARCHAR}, #{id,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{gender,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR}, ",
        "#{openId,jdbcType=VARCHAR}, #{avater,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=VARCHAR}, #{taskId,jdbcType=VARCHAR})"
    })
    int insert(Rescuer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rescuer
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    @Select({
        "select",
        "unit_id, id, name, gender, phone, open_id, avater, status, task_id",
        "from rescuer",
        "where unit_id = #{unitId,jdbcType=VARCHAR}",
          "and id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="unit_id", property="unitId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR),
        @Result(column="avater", property="avater", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="task_id", property="taskId", jdbcType=JdbcType.VARCHAR)
    })
    Rescuer selectByPrimaryKey(@Param("unitId") String unitId, @Param("id") String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rescuer
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    @Select({
        "select",
        "unit_id, id, name, gender, phone, open_id, avater, status, task_id",
        "from rescuer"
    })
    @Results({
        @Result(column="unit_id", property="unitId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR),
        @Result(column="avater", property="avater", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="task_id", property="taskId", jdbcType=JdbcType.VARCHAR)
    })
    List<Rescuer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rescuer
     *
     * @mbg.generated Mon May 06 09:31:02 CST 2019
     */
    @Update({
        "update rescuer",
        "set name = #{name,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "open_id = #{openId,jdbcType=VARCHAR},",
          "avater = #{avater,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "task_id = #{taskId,jdbcType=VARCHAR}",
        "where unit_id = #{unitId,jdbcType=VARCHAR}",
          "and id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Rescuer record);

    @Select({
            "select",
            "unit_id, id, name, gender, phone, open_id, avater, status, task_id",
            "from rescuer",
            "where open_id = #{openId,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="unit_id", property="unitId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
            @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
            @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
            @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR),
            @Result(column="avater", property="avater", jdbcType=JdbcType.VARCHAR),
            @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
            @Result(column="task_id", property="taskId", jdbcType=JdbcType.VARCHAR)
    })
    Rescuer selectByOpenId(@Param("openId") String openId);


    @Select({
            "select",
            "unit_id, id, name, gender, phone, open_id, avater, status, task_id",
            "from rescuer",
            "where task_id = #{taskId,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="unit_id", property="unitId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
            @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
            @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
            @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR),
            @Result(column="avater", property="avater", jdbcType=JdbcType.VARCHAR),
            @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
            @Result(column="task_id", property="taskId", jdbcType=JdbcType.VARCHAR)
    })
    List<Rescuer> selectByTaskId(@Param("taskId") String taskId);

    @Select({
            "select",
            "unit_id, id, name, gender, phone, open_id, avater, status, task_id",
            "from rescuer",
            "where status = '在线' and task_id is null"
    })
    @Results({
            @Result(column="unit_id", property="unitId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
            @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
            @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
            @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR),
            @Result(column="avater", property="avater", jdbcType=JdbcType.VARCHAR),
            @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
            @Result(column="task_id", property="taskId", jdbcType=JdbcType.VARCHAR)
    })
    List<Rescuer> selectFreeRescuer();
}