package com.example.study.mapper;

import com.example.study.object.Task;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    @Delete({
        "delete from task",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    @Insert({
        "insert into task (id, status, ",
        "type, user_open_id, ",
        "rescuer_open_id, chat_group_id, ",
        "receiver_id, event_location_name, ",
        "event_location_coordinate, aid_location_name, ",
        "aid_location_coordinate, aid_route)",
        "values (#{id,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{userOpenId,jdbcType=VARCHAR}, ",
        "#{rescuerOpenId,jdbcType=VARCHAR}, #{chatGroupId,jdbcType=VARCHAR}, ",
        "#{receiverId,jdbcType=VARCHAR}, #{eventLocationName,jdbcType=VARCHAR}, ",
        "#{eventLocationCoordinate,jdbcType=VARCHAR}, #{aidLocationName,jdbcType=VARCHAR}, ",
        "#{aidLocationCoordinate,jdbcType=VARCHAR}, #{aidRoute,jdbcType=LONGVARCHAR})"
    })
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    @Select({
        "select",
        "id, status, type, user_open_id, rescuer_open_id, chat_group_id, receiver_id, ",
        "event_location_name, event_location_coordinate, aid_location_name, aid_location_coordinate, ",
        "aid_route",
        "from task",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_open_id", property="userOpenId", jdbcType=JdbcType.VARCHAR),
        @Result(column="rescuer_open_id", property="rescuerOpenId", jdbcType=JdbcType.VARCHAR),
        @Result(column="chat_group_id", property="chatGroupId", jdbcType=JdbcType.VARCHAR),
        @Result(column="receiver_id", property="receiverId", jdbcType=JdbcType.VARCHAR),
        @Result(column="event_location_name", property="eventLocationName", jdbcType=JdbcType.VARCHAR),
        @Result(column="event_location_coordinate", property="eventLocationCoordinate", jdbcType=JdbcType.VARCHAR),
        @Result(column="aid_location_name", property="aidLocationName", jdbcType=JdbcType.VARCHAR),
        @Result(column="aid_location_coordinate", property="aidLocationCoordinate", jdbcType=JdbcType.VARCHAR),
        @Result(column="aid_route", property="aidRoute", jdbcType=JdbcType.LONGVARCHAR)
    })
    Task selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    @Select({
        "select",
        "id, status, type, user_open_id, rescuer_open_id, chat_group_id, receiver_id, ",
        "event_location_name, event_location_coordinate, aid_location_name, aid_location_coordinate, ",
        "aid_route",
        "from task"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_open_id", property="userOpenId", jdbcType=JdbcType.VARCHAR),
        @Result(column="rescuer_open_id", property="rescuerOpenId", jdbcType=JdbcType.VARCHAR),
        @Result(column="chat_group_id", property="chatGroupId", jdbcType=JdbcType.VARCHAR),
        @Result(column="receiver_id", property="receiverId", jdbcType=JdbcType.VARCHAR),
        @Result(column="event_location_name", property="eventLocationName", jdbcType=JdbcType.VARCHAR),
        @Result(column="event_location_coordinate", property="eventLocationCoordinate", jdbcType=JdbcType.VARCHAR),
        @Result(column="aid_location_name", property="aidLocationName", jdbcType=JdbcType.VARCHAR),
        @Result(column="aid_location_coordinate", property="aidLocationCoordinate", jdbcType=JdbcType.VARCHAR),
        @Result(column="aid_route", property="aidRoute", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Task> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon May 06 09:31:11 CST 2019
     */
    @Update({
        "update task",
        "set status = #{status,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "user_open_id = #{userOpenId,jdbcType=VARCHAR},",
          "rescuer_open_id = #{rescuerOpenId,jdbcType=VARCHAR},",
          "chat_group_id = #{chatGroupId,jdbcType=VARCHAR},",
          "receiver_id = #{receiverId,jdbcType=VARCHAR},",
          "event_location_name = #{eventLocationName,jdbcType=VARCHAR},",
          "event_location_coordinate = #{eventLocationCoordinate,jdbcType=VARCHAR},",
          "aid_location_name = #{aidLocationName,jdbcType=VARCHAR},",
          "aid_location_coordinate = #{aidLocationCoordinate,jdbcType=VARCHAR},",
          "aid_route = #{aidRoute,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Task record);

    @Select({
            "select",
            "id, status, type, user_open_id, rescuer_open_id, chat_group_id, receiver_id, ",
            "event_location_name, event_location_coordinate, aid_location_name, aid_location_coordinate, ",
            "aid_route",
            "from task",
            "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
            @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
            @Result(column="user_open_id", property="userOpenId", jdbcType=JdbcType.VARCHAR),
            @Result(column="rescuer_open_id", property="rescuerOpenId", jdbcType=JdbcType.VARCHAR),
            @Result(column="chat_group_id", property="chatGroupId", jdbcType=JdbcType.VARCHAR),
            @Result(column="receiver_id", property="receiverId", jdbcType=JdbcType.VARCHAR),
            @Result(column="event_location_name", property="eventLocationName", jdbcType=JdbcType.VARCHAR),
            @Result(column="event_location_coordinate", property="eventLocationCoordinate", jdbcType=JdbcType.VARCHAR),
            @Result(column="aid_location_name", property="aidLocationName", jdbcType=JdbcType.VARCHAR),
            @Result(column="aid_location_coordinate", property="aidLocationCoordinate", jdbcType=JdbcType.VARCHAR),
            @Result(column="aid_route", property="aidRoute", jdbcType=JdbcType.LONGVARCHAR)
    })
    Task selectByOpenId(String OpenId);

    @Select({
            "select",
            "id, status, type, user_open_id, rescuer_open_id, chat_group_id, receiver_id, ",
            "event_location_name, event_location_coordinate, aid_location_name, aid_location_coordinate, ",
            "aid_route",
            "from task",
            "where (status = '受理中' or status = '进行中') ",
            "and (receiver_id = #{receiverId,jdbcType=VARCHAR} or receiver_id is null)",
            "and type = #{type,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
            @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
            @Result(column="user_open_id", property="userOpenId", jdbcType=JdbcType.VARCHAR),
            @Result(column="rescuer_open_id", property="rescuerOpenId", jdbcType=JdbcType.VARCHAR),
            @Result(column="chat_group_id", property="chatGroupId", jdbcType=JdbcType.VARCHAR),
            @Result(column="receiver_id", property="receiverId", jdbcType=JdbcType.VARCHAR),
            @Result(column="event_location_name", property="eventLocationName", jdbcType=JdbcType.VARCHAR),
            @Result(column="event_location_coordinate", property="eventLocationCoordinate", jdbcType=JdbcType.VARCHAR),
            @Result(column="aid_location_name", property="aidLocationName", jdbcType=JdbcType.VARCHAR),
            @Result(column="aid_location_coordinate", property="aidLocationCoordinate", jdbcType=JdbcType.VARCHAR),
            @Result(column="aid_route", property="aidRoute", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Task> selectReceiverTasks(@Param("type")String type, @Param("receiverId")String receiverId);
}